# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"6\n\x12\x43\x61lculationRequest\x12\x0f\n\x07number1\x18\x01 \x01(\x05\x12\x0f\n\x07number2\x18\x02 \x01(\x05\"%\n\x13\x43\x61lculationResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\xb3\x01\n\nCalculator\x12O\n\nAddNumbers\x12\x1e.calculator.CalculationRequest\x1a\x1f.calculator.CalculationResponse0\x01\x12T\n\x0fMultiplyNumbers\x12\x1e.calculator.CalculationRequest\x1a\x1f.calculator.CalculationResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALCULATIONREQUEST']._serialized_start=32
  _globals['_CALCULATIONREQUEST']._serialized_end=86
  _globals['_CALCULATIONRESPONSE']._serialized_start=88
  _globals['_CALCULATIONRESPONSE']._serialized_end=125
  _globals['_CALCULATOR']._serialized_start=128
  _globals['_CALCULATOR']._serialized_end=307
# @@protoc_insertion_point(module_scope)
